name: Build And Run Test on Windows

on:
  push:
    branches: [ main ]
  pull_request: 
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  Build_and_Run_GTest:
    name: Build and Run GoogleTest
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install LibTiff
      uses: ilammy/msvc-dev-cmd@v1
      working-directory: ${{github.workspace}}
      shell: cmd
      run: install_win_prereq.bat

    - name: Set variable
      run: |
        echo "TIFF_INCLUDE_DIR=C:/Program Files (x86)/tiff/include" >> $env:GITHUB_ENV
        echo "TIFF_LIBRARY_RELEASE=C:/Program Files (x86)/tiff/lib/tiff.lib" >> $env:GITHUB_ENV
 
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_CLI=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel 2

    - name: Run GTest Suite
      working-directory: ${{github.workspace}}/build
      # Execute tests.  
      run: ./tests/${{env.BUILD_TYPE}}/runAllTests.exe
      

  Build_and_Run_PyTest:
    name: Build and Run PyTest
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
              
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Install Dependencies
      run: python -m pip install --upgrade wheel numpy pandas pytest delvewheel

    - name: Preparing nmake    
        uses: ilammy/msvc-dev-cmd@v1
    
    - name: Install LibTiff
      working-directory: ${{github.workspace}}
      shell: cmd
      run: install_win_prereq.bat

    - name: Set variable
      run: |
        echo "TIFF_INCLUDE_DIR=C:/Program Files (x86)/tiff/include" >> $env:GITHUB_ENV
        echo "TIFF_LIBRARY_RELEASE=C:/Program Files (x86)/tiff/lib/tiff.lib" >> $env:GITHUB_ENV
        echo "C:/Program Files (x86)/tiff/bin" >> $env:GITHUB_PATH
 
    - name: Install Nyxus
      working-directory: ${{github.workspace}}
      shell: cmd
      run: install_win_nyxus.bat

    - name: Run PyTest
      working-directory: ${{github.workspace}}
      run: python3 -m pytest tests/python/